### ISSUE TITLE
Professor's POV

### ISSUE THREAD

**Issue by NeedlesslyLongUserName** [s269731/PULSeBS-Team8#12]
Hi guys, first of all good job!
The thing I would add is a list of all the students in the register attendance section,
maybe each name could be accompanied by a checkbox to check if they are in fact present.
This could be especially helpful for exams in which the student's individual presence in the lectures is evaluated as part of the grade.
Good luck for the next sprint!

**Comment by mtorchiano** [comment]
Confirm the above observation. The system should support a roll call by the teacher that can mark each student as presente (or absent)

**Comment by LucaBarco** [comment]
Good evening,
we have changed the modality to insert attendance in the following way.
When the teacher wants to record the attendance, he can click on a button that opens a modal in which there is the list of booked students.
![Immagine 2020-12-23 164843](https://user-images.githubusercontent.com/51737661/103014774-9e898180-453f-11eb-9390-a454f85dc359.png)

Here he can mark a student as present or absent using a checkbox, then he can save.

![Immagine 2020-12-23 164853](https://user-images.githubusercontent.com/51737661/103014802-a9dcad00-453f-11eb-9904-3c330170386c.png)

![Immagine 2020-12-23 164905](https://user-images.githubusercontent.com/51737661/103014910-d8f31e80-453f-11eb-9bc3-65f32baed028.png)


Once the data are stored, he can still see the list of booked students with an information about the attendance.

![Immagine 2020-12-23 164942](https://user-images.githubusercontent.com/51737661/103014987-f2946600-453f-11eb-89e6-043c353812f6.png)

Could this mechanism be fine?

**Comment by mtorchiano** [comment]
Yes, but please also post on Discord so everybody knows

Marco.
