### ISSUE TITLE
[Team 1] Notification when lecture mode changed

### ISSUE THREAD

**Issue by MinfangLi** [s269731/PULSeBS-Team8#13]
if the  teacher and students of a lecture only via checking homepage to know that the support officer have changed the lecture mode, it seems inconvenient. it seems nice to have a notification to the teacher and students

**Comment by s269731** [comment]
Hi MinfangLi, thank you very much for this feedback.
Actually, your proposal was added as a new story by the PO (story 21-BIS), so we're going to close this issue.
Have a nice day!
Loredana
