### ISSUE TITLE
Improve the design of user card in the navbar.

### ISSUE THREAD

**Issue by gabrielefantini** [s269731/PULSeBS-Team8#14]
![InkedCattura_LI](https://user-images.githubusercontent.com/31799201/102628168-939ead80-4149-11eb-9da8-6e3abfd429f6.jpg)

Maybe you could remove the white margin and change the font size or fill the card with a color different from the navbar to have better contrast.

**Comment by LucaBarco** [comment]
The issue now is fixed. Thanks for the feedback! 

![Immagine 2020-12-22 180247](https://user-images.githubusercontent.com/51737661/102914005-efd23c00-447f-11eb-8d6d-44b223db7bab.png)
