### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Francexi** [s269731/PULSeBS-Team8#2]
I'm Francesco Petronella, acted as Archibald

I really liked the clearness of the interface, but the fonts are too little. Also, it seems that there are too much stuff on screen, that makes everything a bit complex.

Have a nice day

**Comment by MassimoMissio** [comment]
Hi! I'm Massimo Missio and i play the role of Giovanni ( a new Student).
I liked your work but i think that it might be more user friendly if you modify the button for the browsing between the 2 pages that you implement and make it bigger.

**Comment by daniele123321** [comment]
Thanks for the feedback.

> Hi! I'm Massimo Missio and i play the role of Giovanni ( a new Student).
> I liked your work but i think that it might be more user friendly if you modify the button for the browsing between the 2 pages that you implement and make it bigger.

May I kindly ask you to open a separate issue?
