### ISSUE TITLE
Change teacher statistics css styling to show lecture statistics and graph on dfferent rows and bigger dimensions

### ISSUE THREAD

**Issue by s277945** [s269731/PULSeBS-Team8#7]

**Comment by daniele123321** [comment]
They are already shown on separate rows in smaller screen.

**Comment by LucaBarco** [comment]
Issue fixed

![Immagine 2020-12-08 132517](https://user-images.githubusercontent.com/51737661/101483877-1610bb80-3959-11eb-971e-436b118ad55e.png)
