### ISSUE TITLE
Change lecture element on teacher page to show only title and date as preview, then more information after selecting the item

### ISSUE THREAD

**Issue by s277945** [s269731/PULSeBS-Team8#8]

**Comment by LucaBarco** [comment]
Issue fixed

![Immagine 2020-12-08 132214](https://user-images.githubusercontent.com/51737661/101483804-fda0a100-3958-11eb-9dcc-11455dfd2ac8.png)


![Immagine 2020-12-08 132317](https://user-images.githubusercontent.com/51737661/101483814-02655500-3959-11eb-873e-39e2aefeab8f.png)
